# Generated by Django 5.2.9 on 2025-12-08 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_role_user_is_ceo_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ceo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('DistrictCoordinator', 'District Coordinator'), ('BAC/BRCHead', 'BAC/BRC Head'), ('RegionalManager', 'Regional Manager'), ('Director', 'Director'), ('CEO', 'CEO'), ('HR', 'HR Director')], default='Employee', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
