# Generated by Django 5.2.9 on 2025-12-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancereview',
            old_name='feedback',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='performancereview',
            old_name='review_period_end',
            new_name='review_date',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='review_period_start',
        ),
    ]
