# Generated by Django 5.2.9 on 2025-12-04 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_rename_feedback_performancereview_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancereview',
            old_name='employee',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='score',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('RegionalApproved', 'Regional Approved'), ('HeadOfficeApproved', 'Head Office Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
