# Generated by Django 5.2.9 on 2025-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_rename_employee_performancereview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='appraisal_pdf',
            field=models.FileField(blank=True, null=True, upload_to='performance_pdfs/'),
        ),
    ]
